name: Add Label

on:
  repository_dispatch:
    types: [bug-command, feature-command]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if this is a valid slash command dispatch event
            if (!github.event.client_payload || !github.event.client_payload.slash_command) {
              console.log('❌ This workflow should only be triggered by slash command dispatch events');
              core.setFailed('Invalid event trigger - expected slash command dispatch');
              return;
            }
            
            const slashCommand = github.event.client_payload.slash_command;
            const label = slashCommand.command;
            
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: slashCommand.issue.number,
                labels: [label]
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: slashCommand.issue.number,
                body: `✅ Added label \`${label}\` to this ${slashCommand.issue.pull_request ? 'pull request' : 'issue'}.`
              });
            } catch (error) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: slashCommand.issue.number,
                body: `❌ Failed to add label \`${label}\`: ${error.message}`
              });
              core.setFailed(error.message);
            }
