name: Request Review

on:
  repository_dispatch:
    types: [review-command]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review from user
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const args = github.event.client_payload.slash_command.args.unnamed;
            const user = args && args.length > 0 ? args[0] : null;
            
            if (!user) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `❌ Please mention a user to request review. Usage: \`/review @username\``
              });
              core.setFailed('No user mentioned');
              return;
            }
            
            if (!github.event.client_payload.slash_command.issue.pull_request) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `❌ The /review command can only be used on pull requests.`
              });
              core.setFailed('Not a pull request');
              return;
            }
            
            const username = user.replace(/^@/, '');
            
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: github.event.client_payload.slash_command.issue.number,
                reviewers: [username]
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `✅ Requested review from @${username}.`
              });
            } catch (error) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `❌ Failed to request review from @${username}: ${error.message}`
              });
              core.setFailed(error.message);
            }
