name: Assign User

on:
  repository_dispatch:
    types: [assign-command]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign user
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const args = github.event.client_payload.slash_command.args.unnamed;
            const user = args && args.length > 0 ? args[0] : null;
            
            if (!user) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `❌ Please mention a user to assign. Usage: \`/assign @username\``
              });
              core.setFailed('No user mentioned');
              return;
            }
            
            const username = user.replace(/^@/, '');
            
            try {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                assignees: [username]
              });
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `✅ Assigned @${username} to this ${github.event.client_payload.slash_command.issue.pull_request ? 'pull request' : 'issue'}.`
              });
            } catch (error) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.event.client_payload.slash_command.issue.number,
                body: `❌ Failed to assign @${username}: ${error.message}`
              });
              core.setFailed(error.message);
            }
