name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add size label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "size: XS",
              "10": "size: S", 
              "50": "size: M",
              "200": "size: L",
              "500": "size: XL"
            }
